import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useFraud } from '../hooks/useFraud';
import { getFraudReportsAdminApi } from '../api/adminApi';
import { FraudReport } from '../types/fraud';

export const FraudReportPage = () => {
  const { user } = useAuth();
  const fraud = useFraud();
  const [adminReports, setAdminReports] = useState<FraudReport[]>([]);
  const [loadingAdmin, setLoadingAdmin] = useState(false);

  useEffect(() => {
    if (user?.role !== 'admin') {
      return;
    }

    const loadAdminReports = async () => {
      setLoadingAdmin(true);
      try {
        const data = await getFraudReportsAdminApi();
        setAdminReports(data.reports);
      } finally {
        setLoadingAdmin(false);
      }
    };

    void loadAdminReports();
  }, [user]);

  const navigate = useNavigate();
  const reports = user?.role === 'admin' ? adminReports : fraud.reports;
  const latestReport = reports[0] || null;
  const latestReporter = latestReport
    ? latestReport.reported_by_name ||
      (typeof latestReport.reported_by === 'string'
        ? latestReport.reported_by
        : latestReport.reported_by?.name || latestReport.reported_by?._id)
    : null;

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-slate-700 bg-card-dark p-6">
        <h2 className="text-xl font-semibold text-white">AI Fraud Reports</h2>
        <p className="mt-1 text-sm text-slate-400">
          {user?.role === 'admin'
            ? 'All AI-generated fraud reports from users are shown here for review and investigation.'
            : 'Your account activity is continuously scanned for anomalies. When the AI detects suspicious behavior, a fraud report is generated automatically for review.'}
        </p>
      </div>

      <div className="rounded-2xl border border-slate-700 bg-card-dark p-6">
        <h3 className="text-lg font-semibold text-white">Latest AI Fraud Alert</h3>
        {latestReport ? (
          <div className="mt-4 space-y-3 rounded-xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-200">
            <p className="font-medium">Report ID: {latestReport._id}</p>
            {user?.role === 'admin' && latestReporter ? (
              <p>User: {latestReporter}</p>
            ) : null}
            {user?.role === 'admin' && latestReport.reported_by_email ? (
              <p>Email: {latestReport.reported_by_email}</p>
            ) : null}
            <p>Transaction: {latestReport.transaction_id?._id || 'N/A'}</p>
            <p>Risk Score: {latestReport.risk_score}</p>
            <p>Status: {latestReport.status}</p>
            <p>Analysis: {latestReport.ai_analysis || 'Awaiting AI review.'}</p>
            {user?.role !== 'admin' ? (
              <button
                type="button"
                className="mt-3 rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white"
                onClick={() =>
                  navigate('/dispute', {
                    state: {
                      transactionId: latestReport.transaction_id?._id,
                      fraudReportId: latestReport._id
                    }
                  })
                }
              >
                Dispute this report
              </button>
            ) : null}
          </div>
        ) : loadingAdmin && user?.role === 'admin' ? (
          <p className="mt-4 text-sm text-slate-400">Loading AI-generated fraud reports for review...</p>
        ) : (
          <p className="mt-4 text-sm text-slate-400">
            {user?.role === 'admin'
              ? 'No AI-generated fraud reports have been created yet for review.'
              : 'No AI fraud reports have been generated for your activity yet.'}
          </p>
        )}
      </div>

      <div className="rounded-2xl border border-slate-700 bg-card-dark p-6">
        <h3 className="text-lg font-semibold text-white">All AI Fraud Reports</h3>
        {loadingAdmin && user?.role === 'admin' ? (
          <p className="mt-3 text-sm text-slate-400">Loading AI reports generated by the scanner...</p>
        ) : reports.length === 0 ? (
          <p className="mt-3 text-sm text-slate-400">
            {user?.role === 'admin'
              ? 'No AI-generated fraud reports are available yet for review.'
              : 'The AI scanner has not flagged any transactions yet.'}
          </p>
        ) : (
          <ul className="mt-3 space-y-3 text-sm text-slate-200">
            {reports.map((report) => {
              const reporter = report.reported_by_name ||
                (typeof report.reported_by === 'string'
                  ? report.reported_by
                  : report.reported_by?.name || report.reported_by?._id);
              return (
                <li key={report._id} className="rounded-xl border border-slate-800 bg-slate-950 p-4">
                  <p className="font-medium">Report ID: {report._id}</p>
                  {user?.role === 'admin' && reporter ? <p>User: {reporter}</p> : null}
                  {user?.role === 'admin' && report.reported_by_email ? <p>Email: {report.reported_by_email}</p> : null}
                  <p>Status: {report.status}</p>
                  <p>Risk Score: {report.risk_score}</p>
                  <p>Transaction: {report.transaction_id?._id || 'N/A'}</p>
                  {user?.role !== 'admin' ? (
                    <button
                      type="button"
                      className="mt-3 rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white"
                      onClick={() =>
                        navigate('/dispute', {
                          state: {
                            transactionId: report.transaction_id?._id,
                            fraudReportId: report._id
                          }
                        })
                      }
                    >
                      Dispute this report
                    </button>
                  ) : null}
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </div>
  );
};
